### ISSUE TITLE
Validation failing on working samplesheets

### ISSUE THREAD

**Issue by nschcolnicov** [lit-regensburg/samshee#1]
Hi @j4cko, first of all, thank you for spending time developing this tool, it is very usefull. I'm currently working building a nextflow module around your tool for an nf-core demultiplexing pipeline: https://github.com/nf-core/demultiplex/pull/234#pullrequestreview-2229827928.

When testing the tool, I saw that the validation would fail for samplesheets that are working with bclconvert and bcl2fastq, i.e : https://raw.githubusercontent.com/nf-core/test-datasets/demultiplex/testdata/miseq_35147139/miseq_35147139_samplesheet.csv

I see that it fails because in the tool the parse_settings function (from https://github.com/lit-regensburg/samshee/blob/main/src/samshee/sectionedsheet.py) expects key-value pairs in the Settings section. By default, sections that are named "header" or "reads", or are suffixed "settings" are assumed to be settings sections.
So, Reads section is being parsed as a Settings section, but it contains a single integer value rather than key-value pairs, leading to the validation error.

I wanted to ask you if this is the intended behavior, and these are just an older version of samplesheets, or if this is a bug?

Thank you!

**Comment by j4cko** [comment]
Hi, thanks for your feedback. The sample sheets you linked are v1 sample sheets. We used https://github.com/clintval/sample-sheet for parsing these in the past and then had the need to parse v2 sample sheets and this is where the project started. I now realize that v1 parsing could probably easily be added, if there is a good way to distinguish v1 from v2 sample sheets. I'll have a look at it when I return from vacation!

**Comment by j4cko** [comment]
Hi, basic parsing of v1 sheets is now possible. The syntactic difference is only that v1 sheets require an "Array" type (the Reads section). Currently, there is no validation of v1 files other than being in the "sectioned" format. A respective json schema could possibly be based on the [miseq documentation](https://support.illumina.com/content/dam/illumina-support/documents/documentation/system_documentation/miseq/miseq-sample-sheet-quick-ref-guide-15028392-j.pdf)

**Comment by nschcolnicov** [comment]
HI @j4cko, I see, great then, thanks!
