### ISSUE TITLE
Implement a proper CLI

### ISSUE THREAD

**Issue by grst** [lit-regensburg/samshee#2]
Hi, 

great tool and I like that fact that you can provide custom json schemas!

Would be great to have a more extensive command line interface, in particular one that allows to specify additional custom JSON schemas. 

We are integrating this tool into the [nf-core/demultiplex](https://github.com/nf-core/demultiplex) nextflow pipeline and having a CLI would save us writing custom python wrapperscripts:  https://github.com/nf-core/demultiplex/pull/234#discussion_r1711184887

Cheers, 
Gregor

**Comment by j4cko** [comment]
Hi, thanks for your comment. I agree, the CLI is being used mainly for testing, currently, but may serve more purposes. I imagine arguments for output format (sample sheet or json) and for validation schemas.
This may be a good addition I'll look into when I return from vacation.

**Comment by j4cko** [comment]
Hi again, some work has been done towards this, see the [respective section in the README](https://github.com/lit-regensburg/samshee?tab=readme-ov-file#commandline-tool). In particular, validation and conversion from/to json is now possible from a CLI. Let me know if there is something specific you are missing.
